### ISSUE TITLE
Unexpected toast while opening the app on NU Wifi

### ISSUE THREAD

**Issue by harshitbudhraja** [harshitbudhraja/NU-Mess#1]
While opening the app on NU Student Wifi, there is an unexpected error toast which says **Could not retrieve a menu**.

Also, downloading the Mess Menu XLSX file from Settings Menu is unsuccessful on Wifi, but works perfectly when on mobile data.

**Comment by harshitbudhraja** [comment]
Okay, this was due to Cloudflare SSL installed on my website https://arachnis.xyz.
As the university has a single public IP 14.139.242.195, if anyone does something unusual through the network, cloudflare graylists the complete network and hence throws a CAPTCHA everytime we open any website secured by it.
So, to resolve this, I must make changes to my SSL settings.

**Comment by ghost** [comment]
Okay, this was due to Cloudflare SSL installed on my website https://arachnis.xyz.
As the university has a single public IP 14.139.242.195, if anyone does something unusual through the network, cloudflare graylists the complete network and hence throws a CAPTCHA everytime we open any website secured by it.
So, to resolve this, I must make changes to my SSL settings.
